<?php

$finder = (new PhpCsFixer\Finder())
    ->in([
        __DIR__.'/app',
        __DIR__.'/config',
        __DIR__.'/database',
        __DIR__.'/tests',
    ])
    ->exclude([
        'autogenerated_content',
        'tests/fixtures',
        'node_modules',
        'vendor',
        'bootstrap/cache',
    ])
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@PER-CS' => true,
        '@PHP82Migration' => true,
    ])
    ->setFinder($finder)
;
